### ISSUE TITLE
the camera resolution is low which makes the recognition sluggish.

### ISSUE THREAD

**Issue by yonathanendu** [salkuadrat/learning#14]

**Comment by salkuadrat** [comment]
Hi @yonathanendu 

You can use the new updated version, and change the resolutionPreset of InputCameraView, like in this example:

https://github.com/salkuadrat/learning/blob/9129d14cddb23cc177166ef40153e5ab6798bf97/packages/learning_face_detection/example/lib/main.dart#L64
