### ISSUE TITLE
I want to put a condition when it finds a specific value and sends it to another page, but it does not stop sending values ​​to the page

### ISSUE THREAD

**Issue by mohanad87m** [salkuadrat/learning#5]
I want to put a condition when it finds a specific value and sends it to another page, but it does not stop sending values ​​to the page
 ```
` Future<void> _startRecognition(InputImage image) async {
    TextRecognitionState state = Provider.of(context, listen: false);

    if (state.isNotProcessing) {
      state.startProcessing();
      state.image = image;
      state.data = await _textRecognition?.process(image);
      state.stopProcessing();
    }
    ///=======
    if(state.text.length>=12){

      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => fff(state.text)),
      );

      state.stopProcessing();
      state.removeListener(() { state;});
    }`
```

**Comment by salkuadrat** [comment]
Don't check state.text.length outside the scope of if (state.isNotProcessing). You should move it to:

` Future<void> _startRecognition(InputImage image) async {
   TextRecognitionState state = Provider.of(context, listen: false);

   if (state.isNotProcessing) {
     state.startProcessing();
     state.image = image;
     state.data = await _textRecognition?.process(image);

     if(state.text.length>=12){

     Navigator.push(
       context,
       MaterialPageRoute(builder: (context) => fff(state.text)),
     );

     state.stopProcessing();
   }
     state.stopProcessing();
   }
